COMP: Fix dependent scope gcc build error in vtkImageLabelDilate3D
Fix the following error reported when using gcc 9.4.0:

/path/to/Slicer-Release/vtkAddon/vtkImageLabelDilate3D.cxx:82:3: error: need ‘typename’ before ‘std::vector<T>::size_type’ because ‘std::vector<T>’ is a dependent scope
   82 |   std::vector<T>::size_type countForMajority = std::vector<T>::size_type(values.size()/2); // more than this count means majority
      |   ^~~

Note that the change from "template <class T>" to "template <typename T>"
is not strictly needed to fix the error. It was done for sake of consistency
with how VTK filters are defining templates.